### ISSUE TITLE
Multiplatform/ktor artifacts not specified in readme

### ISSUE THREAD

**Issue by mxkmn** [JuulLabs/khronicle#60]
You didn't specify the `khronicle-core` and `khronicle-ktor` artifact in the readme. There is only `khronicle-android` there.

p.s. It seems to be the first logging library that correctly removes strings from a release application. Thanks!

**Comment by mxkmn** [comment]
Hey there! What is `KtorLogger` actually? I think it's worth specifying that in the documentation.

**Comment by twyatt** [comment]
> Hey there! What is `KtorLogger` actually? I think it's worth specifying that in the documentation.

Thanks for the suggestion. Updating via #108.
